import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { spawn, execFileSync } from 'node:child_process';
const out=path.resolve('artifacts/browser');await fs.mkdir(out,{recursive:true});
const report={complete:false,browser:'sandboxed Chromium',checks:[],pageErrors:[],consoleErrors:[],externalRequests:[],downloads:{},timings:[]};
const server=spawn(process.execPath,['scripts/serve.mjs'],{stdio:['ignore','pipe','pipe']});let serverLog='';for(const s of [server.stdout,server.stderr])s.on('data',b=>serverLog+=b);
let ready=false;for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:4173/')).ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,100))}assert(ready,'App server ready');
const browser=await chromium.launch({headless:true,chromiumSandbox:true,...(process.env.CHROME_BIN?{executablePath:process.env.CHROME_BIN}:{})});
report.browserVersion=browser.version();
const cdp=await browser.newBrowserCDPSession(),command=await cdp.send('Browser.getBrowserCommandLine');assert(!command.arguments.some(a=>a==='--no-sandbox'||a==='--disable-setuid-sandbox'));
const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true});await context.tracing.start({screenshots:true,snapshots:true,sources:true});const page=await context.newPage();page.setDefaultTimeout(60000);
context.on('page',p=>p.on('pageerror',e=>report.pageErrors.push(e.message)));page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text())});
await context.route('**/*',route=>{const u=route.request().url();if(/^(http:\/\/127\.0\.0\.1:4173\/|file:|blob:|data:|about:)/.test(u))return route.continue();report.externalRequests.push(u);return route.abort()});
const record=s=>report.checks.push(s);
const fixturePaths=['A','B','C'].map(c=>path.resolve(`fixtures/h5p/module-${c}.h5p`));
let uploads=0;
async function upload(){const started=Date.now();if(uploads++===0){const chooser=page.waitForEvent('filechooser');await page.locator('#choose-files-button').click();await(await chooser).setFiles(fixturePaths)}else await page.locator('#file-input').setInputFiles(fixturePaths);await waitIdle('input loading');await expect(page.locator('.module-card')).toHaveCount(3);report.timings.push({operation:'input loading',milliseconds:Date.now()-started});return ids()}
async function firstPlan(){const [a,b,c]=await upload();await connect(a,2,b);await connect(a,3,c);await page.locator('#validate-button').click();await valid(4);return[a,b,c]}
const metrics=()=>page.locator('#metrics .metric-value strong');
async function waitIdle(operation){await page.waitForFunction(()=>document.getElementById('workspace')?.getAttribute('aria-busy')==='false',null,{timeout:120000});const notice=page.locator('#status-message');assert(!await notice.evaluate(n=>n.classList.contains('error')),operation+': '+await notice.textContent());}
async function valid(routes){const started=Date.now();await waitIdle('composition');report.timings.push({operation:'composition',milliseconds:Date.now()-started});await expect(page.locator('#download-h5p')).toBeEnabled();await expect(metrics()).toHaveText(['12',String(routes),'2','1']);}
async function shot(name,selector){if(selector){await page.locator(selector).scrollIntoViewIfNeeded();await page.locator(selector).screenshot({path:path.join(out,name+'.png')});}else await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});}
async function saveDownload(button,name){const download=page.waitForEvent('download');await page.locator(button).click();const d=await download;await d.saveAs(path.join(out,name));return fs.readFile(path.join(out,name));}
async function saveCase(name,routes){const bytes=await saveDownload('#download-h5p',name+'.h5p');const manifest=JSON.parse(await saveDownload('#download-manifest',name+'.manifest.json'));await saveDownload('#download-report',name+'.report.txt');const sha=createHash('sha256').update(bytes).digest('hex');assert.equal(manifest.output.sha256,sha);assert.equal(manifest.routes.length,routes);assert.deepEqual(manifest.inputs.map(x=>x.sha256),await Promise.all(fixturePaths.map(async p=>createHash('sha256').update(await fs.readFile(p)).digest('hex'))));report.downloads[name]={sha256:sha,size:bytes.length,routeCount:routes};execFileSync('python3',['oracle/verify_package.py',path.join(out,name+'.h5p'),'--case',name==='first'?'first_splice':'shared_c','--report',path.join(out,name+'-oracle.json')],{stdio:'inherit'});execFileSync('python3',['oracle/mutation_checks.py',path.join(out,name+'.h5p'),'--case',name==='first'?'first_splice':'shared_c'],{stdio:'inherit'});execFileSync('python3',['oracle/sanitize_evidence.py',path.join(out,name+'.h5p'),'--case',name==='first'?'first_splice':'shared_c','--report',path.join(out,name+'-sanitized.json')],{stdio:'inherit'});execFileSync('python3',['oracle/verify_provenance.py',path.join(out,name+'.h5p'),path.join(out,name+'.manifest.json'),'--source-a',fixturePaths[0],'--source-b',fixturePaths[1],'--source-c',fixturePaths[2],'--text-report',path.join(out,name+'.report.txt'),'--report',path.join(out,name+'-provenance.json')],{stdio:'inherit'});record(name+' actual UI H5P/JSON/text downloads, archive hash, independent oracle and negative controls');}
async function ids(){return page.locator('.module-card').evaluateAll(nodes=>nodes.map(n=>n.dataset.moduleId))}
async function connect(a,node,b){await page.locator(`[id="exit-${a}-${node}-node"]`).selectOption(b)}
async function noOverflow(label){assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),label+' has no horizontal page overflow');record(label+' no horizontal page overflow')}
try{
 await page.goto('http://127.0.0.1:4173/');await expect(page.locator('html')).toHaveAttribute('lang','ja');await shot('01-desktop-empty');await noOverflow('Japanese desktop');
 await firstPlan();await expect(page.locator('.module-card')).toHaveCount(3);await expect(page.locator('#host-retained')).toContainText('Event staff orientation');record('Actual local-file selection executes in real Worker and validates 12 nodes / 4 routes');
 const sourceImages=page.locator('.module-preview img');await expect(sourceImages).toHaveCount(2);assert(await sourceImages.evaluateAll(xs=>xs.every(x=>x.complete&&x.naturalWidth===96&&x.naturalHeight===64)));await shot('02-desktop-inputs','.input-stage');await shot('03-desktop-connections','.connection-stage');await shot('04-desktop-first','.result-stage');
 await page.locator('#tab-assets').click();await expect(page.locator('#panel-assets .asset-card')).toHaveCount(2);await shot('05-desktop-images','#panel-assets');await page.locator('#tab-routes').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('#tab-nodes')).toBeFocused();await expect(page.locator('#panel-nodes tbody tr')).toHaveCount(12);record('Both decoded map previews, collision provenance, all 12 node mappings and keyboard tabs');
 await page.locator('[data-lang=en]').click();await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page.locator('.module-card').first()).toContainText('Welcome to BranchSplice.');await shot('06-desktop-english','.result-stage');record('English interface retains original authored source text');
 // The real file-input path above is the source of the acceptance exports.
 let [a,b,c]=await ids();await saveCase('first',4);
 await connect(b,2,c);await expect(page.locator('#download-h5p')).toBeDisabled();await connect(b,3,c);await page.locator('#validate-button').dblclick();await valid(6);await saveCase('shared',6);record('Input change immediately disables old downloads; repeated validation click yields one current valid result');
 await page.locator('#tab-routes').click();await shot('07-desktop-shared','.result-stage');
 // Terminal C2 -> B creates an actual graph cycle (B already leads to C).
 await connect(c,2,b);await page.locator('#validate-button').click();await expect(page.locator('#status-message')).toContainText(/cycle|cyclic|CYCLE/i);await expect(page.locator('#download-h5p')).toBeDisabled();record('Cycle fails closed and exports stay disabled');await connect(c,2,'');await page.locator('#validate-button').click();await valid(6);
 await connect(a,2,'');await page.locator('#validate-button').click();await expect(page.locator('#status-message')).toContainText(/unreach|UNREACH/i);await expect(page.locator('#download-h5p')).toBeDisabled();record('Unreachable donor fails closed');await connect(a,2,b);await page.locator('#validate-button').click();await valid(6);
 await page.locator('.module-card').nth(1).locator('.host-button').click();await expect(page.locator('#download-h5p')).toBeDisabled();await page.locator('#validate-button').click();await expect(page.locator('#status-message')).toContainText(/start|opening|START/i);record('Host change clears connections and rejects a nonempty donor start');
 await page.locator('#file-input').setInputFiles([{name:'broken.h5p',mimeType:'application/zip',buffer:Buffer.from('not a zip')},{name:'also.h5p',mimeType:'application/zip',buffer:Buffer.from('not a zip')}]);await expect(page.locator('#status-message')).toHaveClass(/error/);await expect(page.locator('.module-card')).toHaveCount(0);await expect(page.locator('#download-h5p')).toBeDisabled();record('Malformed packages show a recoverable error without retaining previous output');
 await page.locator('#file-input').setInputFiles(fixturePaths);await expect(page.locator('#workspace')).toHaveAttribute('aria-busy','true');await expect(page.locator('#reset-button')).toBeEnabled();await page.locator('#reset-button').click();await page.waitForTimeout(1200);await expect(page.locator('.module-card')).toHaveCount(0);await expect(page.locator('#download-h5p')).toBeDisabled();record('Reset cancels a live Worker file load without stale resurrection');
 await page.locator('#file-input').setInputFiles(fixturePaths);await firstPlan();record('Repeated file selections settle on current input');
 await page.locator('[data-lang=ja]').click();await page.setViewportSize({width:390,height:844});await noOverflow('Japanese mobile');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'08-mobile-top.png')});await shot('09-mobile-inputs','.input-stage');await shot('10-mobile-result','.result-stage');await page.locator('#tab-assets').click();await shot('11-mobile-images','#panel-assets');await noOverflow('Japanese mobile assets');
 await page.locator('.module-card').nth(2).locator('.remove-button').click();await expect(page.locator('.module-card')).toHaveCount(2);await expect(page.locator('#download-h5p')).toBeDisabled();record('Removing a module revokes old export state');
 // The deliverable is a standalone file, so exercise file:// rather than only HTTP.
 await page.goto(pathToFileURL(path.resolve('dist/index.html')).href);await page.setViewportSize({width:1440,height:1050});await firstPlan();await shot('12-standalone-file','.result-stage');record('Standalone HTML works from file:// with local H5P inputs, embedded Worker and no network');
 assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.externalRequests,[]);report.complete=true;
}catch(error){report.failure=error.stack;await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});await fs.writeFile(path.join(out,'failure.html'),await page.content()).catch(()=>{});throw error}
finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');await fs.writeFile(path.join(out,'browser-command.json'),JSON.stringify(command,null,2));await fs.writeFile(path.join(out,'server.log'),serverLog);await context.tracing.stop({path:path.join(out,'trace.zip')});await browser.close();server.kill('SIGTERM')}
