import express from 'express';
import upload from 'express-fileupload';
import {h5pAjaxExpressRouter} from '@lumieducation/h5p-express';
import defaultRendererModule from '@lumieducation/h5p-server/build/src/renderers/default.js';
import playerRendererModule from '@lumieducation/h5p-server/build/src/renderers/player.js';
import {context,user,runtime} from './context.mjs';
import path from 'node:path';
import {writeFile,mkdir} from 'node:fs/promises';
const {editor,player,config,i18next}=await context();
const renderer=defaultRendererModule.default??defaultRendererModule;
editor.setRenderer(model=>renderer(model).replaceAll('new ns.Editor(undefined, undefined, $editor[0])',"new ns.Editor('H5P.BranchingScenario 1.8', undefined, $editor[0])").replaceAll('$create.show();','window.nativeEditor=h5peditor; $create.show();'));
const playerRenderer=playerRendererModule.default??playerRendererModule;
player.setRenderer(model=>{delete model.integration.user;return playerRenderer(model)});
const app=express();
app.use((req,res,next)=>{res.setHeader('Content-Security-Policy',"script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' 'unsafe-inline'; frame-src 'self' blob:; connect-src 'self'; font-src 'self' data:; img-src 'self' data: blob:; media-src 'self' data: blob:; object-src 'none'");next()});
app.use((req,res,next)=>{const port=process.env.PORT??'8080';if(![`127.0.0.1:${port}`,`localhost:${port}`].includes(req.get('host'))||req.get('sec-fetch-site')==='cross-site'||(req.get('origin')&&req.get('origin')!==`http://127.0.0.1:${port}`&&req.get('origin')!==`http://localhost:${port}`))return res.status(403).send('Local same-origin verification only');next()});
app.use(express.json({limit:'20mb'}));app.use(express.urlencoded({extended:true}));app.use(upload({limits:{fileSize:128*1024*1024},abortOnLimit:true}));
app.use((req,res,next)=>{req.user=user;next()});app.use((req,res,next)=>{req.language='en';req.languages=['en'];req.t=i18next.getFixedT('en');next()});
app.get('/favicon.ico',(req,res)=>res.status(204).end());
const editorPreferences=new Map();
const preferenceKeys=new Set(['h5p-editor-branching-scenario-tour-v1-seen','h5p-editor-branching-scenario-information-content-tour-v1-seen','h5p-editor-branching-scenario-branching-content-tour-v1-seen','h5p-editor-branching-scenario-preview-info-popup-v1-seen']);
app.all('/h5p/contentUserData/0/:key/0',(req,res,next)=>{if(!preferenceKeys.has(req.params.key))return next();if(req.method==='POST')editorPreferences.set(req.params.key,req.body.data==='true');res.json({success:true,data:editorPreferences.has(req.params.key)?JSON.stringify(editorPreferences.get(req.params.key)):false})});
app.get('/health',(req,res)=>res.json({ok:true,core:config.coreApiVersion}));
app.get('/',(req,res)=>res.send('<html><head><meta charset="utf-8"><title>BranchSplice native feasibility</title></head><body><h1>Native H5P authoring gate</h1><p>Official Lumi10.0.4 / Core1.27 / BranchingScenario1.8.14</p><a href="/h5p/new">Create native scenario</a><form action="/import" method="post" enctype="multipart/form-data"><label>Import editable H5P <input type="file" name="package" accept=".h5p"></label><button>Import</button></form></body></html>'));
app.post('/import',async(req,res,next)=>{try{const r=await editor.uploadPackage(req.files.package.data,user);const id=await editor.saveOrUpdateContent(undefined,r.parameters,r.metadata,`${r.metadata.mainLibrary} ${r.metadata.preloadedDependencies.find(x=>x.machineName===r.metadata.mainLibrary).majorVersion}.${r.metadata.preloadedDependencies.find(x=>x.machineName===r.metadata.mainLibrary).minorVersion}`,user);res.redirect(`/h5p/edit/${id}`);}catch(e){next(e)}});
app.get('/h5p/new',async(req,res,next)=>{try{res.send(await editor.render(undefined,'en',user))}catch(e){next(e)}});
app.get('/h5p/edit/:id',async(req,res,next)=>{try{res.send(await editor.render(req.params.id,'en',user))}catch(e){next(e)}});
for(const route of ['/h5p/new','/h5p/edit/:id']) app.post(route,async(req,res,next)=>{try{const id=await editor.saveOrUpdateContent(req.params.id,req.body.params.params,req.body.params.metadata,req.body.library,user);res.send(JSON.stringify({contentId:id}))}catch(e){next(e)}});
app.get('/h5p/play/:id',async(req,res,next)=>{try{res.send(await player.render(req.params.id,user,'en',{showDownloadButton:true,showFrame:true,showH5PIcon:true,showLicenseButton:true}))}catch(e){next(e)}});
app.get('/export/:id',async(req,res,next)=>{try{res.setHeader('Content-Disposition',`attachment; filename="${req.params.id}.h5p"`);res.setHeader('Content-Type','application/zip');await editor.exportContent(req.params.id,res,user)}catch(e){next(e)}});
app.use('/h5p',h5pAjaxExpressRouter(editor,path.join(runtime,'core'),path.join(runtime,'editor'),undefined,'en'));
app.use((error,req,res,next)=>{console.error(error);res.status(500).send(error.stack??String(error))});
app.listen(Number(process.env.PORT??8080),'127.0.0.1',()=>console.log('Native feasibility server listening on127.0.0.1:8080'));
