import express from 'express';
import upload from 'express-fileupload';
import middleware from 'i18next-http-middleware';
import {h5pAjaxExpressRouter} from '@lumieducation/h5p-express';
import defaultRendererModule from '@lumieducation/h5p-server/build/src/renderers/default.js';
import {context,user,runtime} from './context.mjs';
import path from 'node:path';
import {writeFile,mkdir} from 'node:fs/promises';
const {editor,player,config,i18next}=await context();
const renderer=defaultRendererModule.default??defaultRendererModule;
editor.setRenderer(model=>renderer(model).replaceAll('new ns.Editor(undefined, undefined, $editor[0])',"new ns.Editor('H5P.BranchingScenario 1.8', undefined, $editor[0])").replaceAll('$create.show();','window.nativeEditor=h5peditor; $create.show();'));
const app=express();
app.use(express.json({limit:'20mb'}));app.use(express.urlencoded({extended:true}));app.use(upload({limits:{fileSize:128*1024*1024},abortOnLimit:true}));
app.use((req,res,next)=>{req.user=user;next()});app.use(middleware.handle(i18next));
app.get('/health',(req,res)=>res.json({ok:true,core:config.coreApiVersion}));
app.get('/',(req,res)=>res.send('<html><head><meta charset="utf-8"><title>BranchSplice native feasibility</title></head><body><h1>Native H5P authoring gate</h1><p>Official Lumi10.0.4 / Core1.27 / BranchingScenario1.8.14</p><a href="/h5p/new">Create native scenario</a><form action="/import" method="post" enctype="multipart/form-data"><label>Import editable H5P <input type="file" name="package" accept=".h5p"></label><button>Import</button></form></body></html>'));
app.post('/import',async(req,res,next)=>{try{const r=await editor.uploadPackage(req.files.package.data,user);const id=await editor.saveOrUpdateContent(undefined,r.parameters,r.metadata,`${r.metadata.mainLibrary} ${r.metadata.preloadedDependencies.find(x=>x.machineName===r.metadata.mainLibrary).majorVersion}.${r.metadata.preloadedDependencies.find(x=>x.machineName===r.metadata.mainLibrary).minorVersion}`,user);res.redirect(`/h5p/edit/${id}`);}catch(e){next(e)}});
app.get('/h5p/new',async(req,res,next)=>{try{res.send(await editor.render(undefined,'en',user))}catch(e){next(e)}});
app.get('/h5p/edit/:id',async(req,res,next)=>{try{res.send(await editor.render(req.params.id,'en',user))}catch(e){next(e)}});
for(const route of ['/h5p/new','/h5p/edit/:id']) app.post(route,async(req,res,next)=>{try{const id=await editor.saveOrUpdateContent(req.params.id,req.body.params.params,req.body.params.metadata,req.body.library,user);res.send(JSON.stringify({contentId:id}))}catch(e){next(e)}});
app.get('/h5p/play/:id',async(req,res,next)=>{try{res.send(await player.render(req.params.id,user,'en',{showDownloadButton:true,showFrame:true,showH5PIcon:true,showLicenseButton:true}))}catch(e){next(e)}});
app.get('/export/:id',async(req,res,next)=>{try{res.setHeader('Content-Disposition',`attachment; filename="${req.params.id}.h5p"`);res.setHeader('Content-Type','application/zip');await editor.exportContent(req.params.id,res,user)}catch(e){next(e)}});
app.use('/h5p',h5pAjaxExpressRouter(editor,path.join(runtime,'core'),path.join(runtime,'editor'),undefined,'en'));
app.use((error,req,res,next)=>{console.error(error);res.status(500).send(error.stack??String(error))});
app.listen(Number(process.env.PORT??8080),'127.0.0.1',()=>console.log('Native feasibility server listening on127.0.0.1:8080'));
